name: Build

on:
  push:

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Install .NET 10 SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.302

      - name: Restore
        run: dotnet restore "Linkpi Monitor.slnx"

      - name: Build
        run: dotnet build "Linkpi Monitor.slnx" --configuration Release --no-restore
